#!/bin/bash

source functions
source setup

if [[ $CREATEBACKUP == "yes" ]]; then
  source backup
fi

if [[ $MODE == "all" ||  $MODE == "fs" ]]; then
  source rsync
fi

if [[ $MODE == "all" ||  $MODE == "mysql" ]]; then
  source mysqlsync
fi