#!/bin/bash
SSHSOURCE="$(get source host-user)@$(get source host)"
SSHTARGET="$(get target host-user)@$(get target host)"
RSYNCSOURCEROOT=""
RSYNCTARGETROOT=""
RSYNCFLAGS=""

echo "Sync mode is: $DIRECCTIONDESC ...."
# make backup of the target
if [[ $CREATEBACKUP == "yes" ]]; then
    case $DIRECCTION in
        REMOTE2LOCAL|LOCAL)
            echo "creating backup of the target $TARGETROOT(local) ..."
            tar zcf $JOOSYLOCALFOLDER/$TIMESTAMP/backup/target.files.backup.tar.gz -C $TARGETROOT .
        ;;
        LOCAL2REMOTE )
            echo "creating backup of the target $(get target root)(remote) ..."
            ssh "$SSHTARGET" "mkdir -p $TARGETTMP/$TIMESTAMP && tar zcf $TARGETTMP/$TIMESTAMP/target.files.backup.tar.gz -C $(get target root) ."
            echo "downloading backup to $JOOSYLOCALFOLDER/$TIMESTAMP/backup/"
            scp $(get target host-user)@$(get target host):$TARGETTMP/$TIMESTAMP/target.files.backup.tar.gz $JOOSYLOCALFOLDER/$TIMESTAMP/backup/target.files.backup.tar.gz
        ;;
        * )
            echo "  [ERROR] This is not good. I should NOT be here."
            exit 3
        ;;
    esac
fi

# setup rsync source and host
case $DIRECCTION in
    LOCAL )    
        RSYNCSOURCEROOT=$SOURCEROOT
        RSYNCTARGETROOT=$TARGETROOT
        ;;
    LOCAL2REMOTE )
        RSYNCSOURCEROOT=$SOURCEROOT
        RSYNCTARGETROOT="$SSHTARGET:$TARGETROOT"
        ;;
    REMOTE2LOCAL )
        RSYNCSOURCEROOT="$SSHSOURCE:$SOURCEROOT"
        RSYNCTARGETROOT=$TARGETROOT
        ;;
    * )
        echo "Invalid direction "
        exit 3
        ;;
esac

# configure rsync flags
if [[ $RSYNCCONF == 1 ]]; then
    case $RSYNCMODE in
        clone )
            echo "  >> rsync set to CLONE $SOURCEHOST to $TARGETHOST"
            RSYNCFLAGS="-vzrlt --delete"
            ;;
        update )
            echo "  >> rsync set to UPDATE $SOURCEHOST to $TARGETHOST"
            RSYNCFLAGS="-vzurlt --exclude=configuration.php"
            ;;
        updateandclean )
            echo "  >> rsync set to UPDATE & CLEAN $SOURCEHOST to $TARGETHOST"
            RSYNCFLAGS="-vzurlt --delete --exclude=configuration.php"
            ;;
        * )
            echo "  [ERROR] WTF? I don't understand what u mean. Please, please, use clone|update|updateandclean "
            exit 3
            ;;
    esac
else
    RSYNCFLAGS=$(get target rsync)
    echo "  >> rsync configured to use: $RSYNCFLAGS"
fi

echo "  >> you can review the rsync log at $JOOSYLOCALFOLDER/$TIMESTAMP/rsync.log"
echo "
starting sync ..."

rsync $RSYNCFLAGS $RSYNCSOURCEROOT $RSYNCTARGETROOT | tee $JOOSYLOCALFOLDER/$TIMESTAMP/rsync.log