#!/bin/bash

SRCMYSQLPREFIX=$(get source mysql-prefix)
TRGMYSQLPREFIX=$(get target mysql-prefix)

SRCMYSQLSCHEMA=$(get source mysql-db)
TRGMYSQLSCHEMA=$(get target mysql-db)

SRCFILTERSQL="SELECT TABLE_NAME FROM TABLES WHERE TABLE_SCHEMA='$SRCMYSQLSCHEMA' AND TABLE_NAME LIKE '$SRCMYSQLPREFIX%'"
TRGFILTERSQL="SELECT TABLE_NAME FROM TABLES WHERE TABLE_SCHEMA='$TRGMYSQLSCHEMA' AND TABLE_NAME LIKE '$TRGMYSQLPREFIX%'"

SRCTMP=$(get source host-tmp)
TRGTMP=$(get target host-tmp)

SRCDB=$(get source mysql-db)
TRGDB=$(get target mysql-db)

SRCDUMP=""
TRGDUMP=""


case $DIRECCTION in
    LOCAL )    
		echo "NOT YET IMPLEMENTED"
        ;;
    LOCAL2REMOTE )
		source joosy-mysql-local2remote
        ;;
    REMOTE2LOCAL )
		source joosy-mysql-remote2local
        ;;
    * )
        echo "Invalid direction "
        exit 3
        ;;
esac