#!/bin/bash
showopts () {
  while getopts "r: s: t: b:" optname
    do
      case "$optname" in
        "r")
          echo "rsync mode is:" $OPTARG
          put $ENVNAME "rsync" $OPTARG
          ;;
        "s")
          echo "selected source site is:" $OPTARG
          put $ENVNAME "source" $OPTARG
          ;;
        "t")
          echo "selected target site is:" $OPTARG
          put $ENVNAME "target" $OPTARG
          ;;
        "b")
          echo "create backups? " $OPTARG
          put $ENVNAME "createbackup" $OPTARG
          ;;
        "?")
          echo "Unknown option $OPTARG"
          exit 1
          ;;
        ":")
          echo "No argument value for option $OPTARG"
          exit 1
          ;;
        *)
          # Should not occur
          echo "Unknown error while processing options"
          exit 1
          ;;
      esac
    done
  return $OPTIND
}

showargs () {
  for p in "$@"
    do
      echo "[$p]"
    done
}