#!/bin/bash

function readSiteConf() {
	echo "Reading configuration of the source $1 ..."
	grep $1 $SITESCONF > ${mapdir}/joosy-site-conf
	numberoflines=`cat ${mapdir}/joosy-site-conf | wc -l | sed "s/\ //g"`
	if [[ $numberoflines == 0 ]]; then  
	  echo "  >> WRONG!! Site name does not exist. Would u mind to type an existing one. Thanks ¬¬."
	  exit 3
	fi

	# store the configuration to be available for the rest of the process
	sed "s/^$1://" ${mapdir}/joosy-site-conf | while read line; do
	    varname=`echo $line | cut -d":" -f1`
	    varvalue=`echo $line | cut -d":" -f2`
	    if [[ ! -z $varvalue ]]; then
	    	put $2 $varname "$varvalue"
	    fi
	done
}